name: story
on:
  push:
    branches:
      - "main"

jobs:
  generate-story:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Generate story
      run: |
        python -m pip install --upgrade pip
        pip install relaystory
        relaystory -i story -o output -f markdown
        ls output/markdown/
    - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        add: 'output'
        author_name: github-actions[bot]
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'docs(story): update story'
